# Generated by Django 4.1.4 on 2022-12-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IEAPP', '0002_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IEAPP.zone'),
        ),
    ]
